[Common]
Login=0
Password=
Server=
KeepPrivate=0
NewsEnable=0

[Tester]
TestExpert=__EXPERT_NAME__.ex5
TestExpertParameters=__SET_FILE__
TestSymbol=__SYMBOL__
TestPeriod=__PERIOD__
TestModel=0
TestFromDate=__FROM_DATE__
TestToDate=__TO_DATE__
TestOptimization=false
TestReport=__REPORT_PATH__
TestReplaceReport=true
TestShutdownTerminal=true
